package com.example.financeapp.exception;

public enum ApiErrorCode {

    // AUTH / USER
    USER_NOT_FOUND,
    USER_DELETED,             // 🔥 thêm mới
    EMAIL_ALREADY_EXISTS,
    ACCOUNT_LOCKED,
    INVALID_CREDENTIALS,
    GOOGLE_ACCOUNT_ONLY,
    GOOGLE_TOKEN_INVALID,     // 🔥 thêm mới
    PASSWORD_NOT_SET,
    PASSWORD_SAME_AS_OLD,
    PASSWORD_ALREADY_SET,
    INVALID_RESET_TOKEN,
    RESET_TOKEN_EXPIRED,

    // USER MANAGEMENT
    USER_ALREADY_LOCKED,
    USER_ALREADY_UNLOCKED,
    CANNOT_MODIFY_SELF,
    CANNOT_DOWNGRADE_LAST_ADMIN,
    INVALID_ROLE_CHANGE,

    // OTP
    OTP_INVALID,
    OTP_EXPIRED,
    OTP_NOT_FOUND,

    // VALIDATION
    VALIDATION_ERROR,

    // PERMISSION
    ACCESS_DENIED,

    // SYSTEM
    INTERNAL_ERROR
}
